---
apiVersion: v1
kind: Service
metadata:
  name: cloudflare-ext-authz-service
  labels:
    app.kubernetes.io/name: cloudflare-ext-authz-service
spec:
  ports:
    - name: grpc
      port: 9090
      targetPort: grpc
  selector:
    app.kubernetes.io/name: cloudflare-ext-authz-service
