name: CI

on:
  push:
    branches: master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set Build Args
        id: set_build_args
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            mrsaints/cloudflare-ext-authz-service:latest
            mrsaints/cloudflare-ext-authz-service:${{ steps.set_build_args.outputs.sha_short }}
          build-args: |
            BUILD_VERSION=${{ steps.set_build_args.outputs.sha_short }}
      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
