name: CI

on:
  push:
    branches: master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set Build Args
        id: set_build_args
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            mrsaints/cloudflare-ext-authz-service:latest
            mrsaints/cloudflare-ext-authz-service:${{ env.sha_short }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6
          build-args: |
            BUILD_VERSION=${{ env.sha_short }}
      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
